spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        formal-sql: true
        show-sql: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret:
            scope: profile, email, https://www.googleapis.com/auth/youtube
          naver:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email, propfile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
test:
  sample:
    username: babo
    password: dfdfqq11
    own-names:
      - dfkldf
      - qqkkccc
      - vvbbb
